### ISSUE TITLE
ID Lookup only enumerates Flaming Cliffs Aircraft

### ISSUE THREAD

**Issue by synackack** [charlestytler/streamdeck-dcs-interface#1]
DCS 2.5.6 Openbeta
Install in steam\steamapps\common\DCSWorld

Flaming Cliffs aircraft are the only device ID's to enumerate. Everything else is blank. 

It would appear that Mods\Aircrfaft\%Aircraftname%\Cockpit\Scripts\clickabledata.lua has been moved up one directory to \Cockpit\. 

A location to change absolute URL would be handy.

**Comment by charlestytler** [comment]
@synackack Thanks for the issue report, and also including your install info. The variability of clickabledata.lua location across aircraft modules is already accounted for, but I was not accounting for Steam installation's directory naming of "DCSWorld" instead of "DCS World".

That string is searched for in the Lua file include paths that the aircraft modules call, which I have to override if it is a relative path in order to build the clickabledata table from a different working directory.

Note: I've added cached info in my v1.0.1 release that should also alleviate the problem temporarily until I release this v1.0.2 with the proper fix.

**Comment by synackack** [comment]
I pulled 1.0.2, so far this is working.
