### ISSUE TITLE
A-10C heading knob

### ISSUE THREAD

**Issue by jydoulliez** [charlestytler/streamdeck-dcs-interface#10]
I am unable to increase the value set by the A-10C HSI heading knob by a very small value. It is defined as a type LEV in DCS interface, with values between 0 and 1. But to be able to change heading degree by degree I need to change this floating point value by a very small amount (should be 1/360, it seems to be 0.0016 or something like that). When I put in Stream Deck an "Incremental input (text above)", with Button ID 3001, Device and DCS ID 45, and I change the "Increment by Value" to 0.0016, first the title text is incremented by a larger (and variable) value, and I am also unable to change the direction of rotation by putting a negative value.

The course knob which is similar seems to have the same problem – but for a short moment I could see it work correctly.

What am I doing wrong ? Isn't there a kind of data corruption ? I hope I was clear enough; thanks anyway for this beautiful plugin.

**Comment by thomsonba** [comment]
Incremental is not suitable for the LEV type of control.  Your subsequnent button presses will rotate the knob at ever accelerating rates!  I am testing a normal momentary switch with a small value to spin the hdg bug + and -   I will update you if I get it working.

**Comment by charlestytler** [comment]
Thanks @thomsonba for the working example for this item. For some LEV item types they expect a constant increment/decrement value, and an absolute value can't be commanded. Therefore, the increment type button is not suitable because it reads the current value of the item and adds an increment to it (thus running into the accelerating rates mentioned), and expects to be able to command a specific value between 0-1 as you were assuming. So far the HSI/CRS knobs, some Radio tuners, and Radio channel selectors have been identified to behave this way. Whereas volume knobs and some other Radio tuners, like the ILS mentioned in #11 expect the increment type.

I've tried to add some documentation in the ID Lookup window and Help contents that mentions this discrepancy in #13, but for the time being I've been using trial and error to choose between the two methods.

**Comment by charlestytler** [comment]
Closing as a working solution within the plugin's capabilities is available and I am not aware of unique characteristics per clickabledata item that could be used to identify these LEV discrepancies.

**Comment by jydoulliez** [comment]
Good to know ! Many thanks to both of you.
