### ISSUE TITLE
A10C TACAN and ILS selector workarounds

### ISSUE THREAD

**Issue by thomsonba** [charlestytler/streamdeck-dcs-interface#11]
I found the following setting works corectly for TACAN selectors, increment 1 and -1
![sd1](https://user-images.githubusercontent.com/11908780/81474307-ccc78480-922e-11ea-8845-814e32435607.png)

For the ILS KHZ values the 1 -1 values don't work!  **I found +/- 0.09 works ok!**
![sd2](https://user-images.githubusercontent.com/11908780/81474383-3fd0fb00-922f-11ea-93a6-121ad5018b3c.png)

**Comment by charlestytler** [comment]
I did some testing with these and I can't seem to find a pattern in consistency between DCS clickable items of LEV type that follow the increment rules, or only pay attention to an increasing or decreasing value (where momentary button with release disabled works better). My suspicion is that it has something to do with radio frequency/channel values that need more functionality than just being tied to a 0-1 value.

For the TACAN it seems to just respond to positive value to increase, or non-positive (<=0) values to decrease. It also is listed as range from 0-1, but the 10's value goes up to a max value of 12, and the reported value just wraps around to +0.2 to account for that (I'm not sure if this is just DCS or the export script). So it is probably best handled with two momentary buttons for increase/decrease.

For the ILS, the odd value necessary is needed because it seems to follow the continuous range expected of an axis similar to the Volume inputs, where the increment will adjust sensitivity. So it is better handled with an increment, and allows for the "cycle to beginning" option if desired.

I'll try to add some mentions of this in the instructions, but I'm not sure how best to describe it for all items other than trial and error.

**Comment by charlestytler** [comment]
Closing as a working solution within the plugin's capabilities is available and I am not aware of unique characteristics per clickabledata item that could be used to identify these LEV discrepancies.
