### ISSUE TITLE
Display Current SW Version Number 

### ISSUE THREAD

**Issue by tastler** [charlestytler/streamdeck-dcs-interface#15]
Hi
thank you for this awesome plugin. 

Is it possible, to indicate the current release version of your plugin within StreamDeck - perhaps on the property inspector pages or the help page?

BR

**Comment by charlestytler** [comment]
Hi @tastler I've added details to the README under the "Version Update" section on how to find the version number of installed plugins. Prior to the current v1.0.3 release I just had "v1.0" listed, but since 31c11eecbd6114585db9c1aed080b76199ae4f2b I will keep the version reported there up to date with each minor release.

I'll consider adding it to the Help page to make it more visible as you're not the first person to have asked.

Commit e042a17607eb9e762fa9973a936cbb75b5265aca adds the following to README:
> Identify installed version number:
To see the version of the plugin installed on the StreamDeck, click the "More Actions..." button, each installed plugin will have the author and version number printed below its title.
