### ISSUE TITLE
Trouble with getting A-10C VHF AM Radios to work as expected (probably applies to the other radios in it as well)

### ISSUE THREAD

**Issue by jkaryan** [charlestytler/streamdeck-dcs-interface#20]
Made an unlisted YouTube video to showcase the problem:

https://www.youtube.com/watch?v=bZjL7zCL60Q

### Description
The gist of the issues is as follows: I'm attempting to make the radios adjustable with single key presses to change each frequency dial, and use the "Title Text Change on DCS Update Settings" functionality to make the frequency show up on the Stream Deck.
The main issue I'm running into is threefold:
-The 1st dial for the VHF frequency goes from 3-15 in steps of 1 (in-game displayed values in the cockpit) for a total of 12 different values, but the ID lookup shows the dial as being a min 0 to max 1 with 0.1 steps one, which is only enough for 11 steps. 
-Using the "Display string unaltered" setting to monitor the value of the DCS ID doesn't even go to 1.00 after 0.90, but reverts back to 0.00 (regardless of whether the "Allow cycling to beginning" tickbox is selected), so in reality you only have 10 values
-Apart from the 0.90 -> 0.00 issue above, when clicking the dial in-game the values go up in steps of 0.10 as expected, but when actually using the Stream Deck button, the first press goes from 0.00 to 0.10 (1 step), second goes from 0.10 to 0.40 (3 steps), and third goes from 0.40 to 0.00 again (6 steps).

Additionally (not in the video), if I set the value to 0.20 by using in-game mouse commands, and then press the Stream Deck button, the value goes from 0.2 to 0.6 (adding 4 steps, instead of 3 like when starting from 0.10 above), and when setting it to 0.30 the same way, it goes from 0.30 to 0.80 with the Stream Deck (5 steps).

Quite flabbergasted by this. The range being obviously wrong seems like a DCS Export issue, but the steps going haywire when used via Stream Deck could be either.

**Comment by charlestytler** [comment]
Hi, another user has actually run into this recently as well. For some of the rotary dials, especially radios it seems that a Momentary push button sending the same value will command them correctly, instead of the increment commands. The values for the digits need to be read from an export of the radio frequency. I believe what is happening when it changes from 0.9 back to 0.0 is this value correspond with the knob turning animation and not the actual displayed digit, but that’s just a guess as I haven’t investigated that further. 

I shared an example way of getting the frequency as individual digits included from the export on the DCS forums here (although it’s not a fully polished fix): https://forums.eagle.ru/forum/english/dcs-world-topics/input-and-output/271902-new-streamdeck-plugin?p=6453720#post6453720
