### ISSUE TITLE
Downloading the installer for the stream deck plug in.

### ISSUE THREAD

**Issue by Macman12** [charlestytler/streamdeck-dcs-interface#34]
Charles - Instructions have been super simple up until installing the installer for the stream deck plug in.  When I try to download the installer, I just get a message to download the link, but nothing downloads.  Would you be able to clarify this process for me please?  

This is all that I get.

com.ctytler.dcs

THanks.

**Comment by charlestytler** [comment]
It looks like you got this figured out here:
https://forums.eagle.ru/topic/230609-new-streamdeck-plugin/?do=findComment&comment=4689995

Perhaps the file extension `.streamDeckPlugin` got messed up in the download. Feel free to re-open if there's still an unresolved issue, otherwise I'll close this.

**Comment by davidp57** [comment]
I've a (I think) similar problem when I share my profiles (.streamDeckProfile) through Discord, they end up with the extension .streamDeckProf which of course is wrong.
