### ISSUE TITLE
conflict with VLEDCONTROL

### ISSUE THREAD

**Issue by fakirsu** [charlestytler/streamdeck-dcs-interface#56]
Hello,
New software has just been released to exchange information between DCS World and VIRPIL brand hardware.
[](https://forum.virpil.com/index.php?/topic/3903-vledcontrol-for-dcs-control-the-leds-of-your-virpil-devices/)
[](https://github.com/Nereid42/VLEDCONTROL/)

Unfortunately, after installing VLEDCONTROL, Streamdeck-dcs-interface no longer works at all: no more feedback on the StreamDeck.

Here is what I then tried:
- Complete removal of VLEDCONTROL and update of the initial parameters of Streamdeck-dcs-interface using the "Enabling Both DCS Interface & Ikarus" method
- Reinstallation of VLEDCONTROL
- VLEDCONTROL then works normally with DCS.
- On the other hand, Streamdeck-dcs-interface still does not work, even when the VLEDCONTROL application is not running.
- I specify that with each test or modification, I close and relaunch DCS World.

The developer of Vledcontrol does not see where the problem could come from.
Do you have an idea ?

Before concluding, I wanted to thank you very very much once again for your tool which is of immense service to me when I am on a DCS mission in my helicopter ;-)

**Comment by charlestytler** [comment]
Sorry, there's quite a bit of disorganization in the export scripts made by different people, some don't work well with others if they overwrite or block access to a resource. Since I've decided to use existing projects for the plugin backend I don't have ability to modify them myself. The best I can recommend is try reordering the scripts within your Export.lua file to see if there is an order where they work well together.

Since DCS-ExportScripts is no longer maintained I've been working on transitioning to the DCS-BIOS backend which generally is more reliable I believe. You can follow progress of that in #41.
